modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "simply_screens"
version = "${version}"
displayName = "Simply Screens"
authors = "nstut"
description = '''
Adds configurable screen blocks that display images from local files or the web. Build dynamic multi-block displays up to 64x64, link screens into synchronized networks with a shared Screen ID, and manage media in-game with secure upload and download support.
'''
#logoFile = ""

[[dependencies.simply_screens]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simply_screens]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simply_screens]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"