modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
issueTrackerURL = "https://github.com/nstut/simply-screens/issues"
license = "MIT"

[[mods]]
modId = "simplyscreens"
version = "${version}"
displayName = "Simply Screens"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simply-screens"
authors = "nstut"
description = '''
A simple mod that adds screens to display images from a URL.
'''
#logoFile = ""

[[dependencies.simplyscreens]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplyscreens]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplyscreens]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
